

name: PHP Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:                                    
  lint:                                     
   name: PHP Lint             
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2     

     - name: Setup PHP
       uses: /setup-php@v2            
       with:
         php-version: '7.4'                  

     - name: PHP lint
       run: php -l /calcuator.php &> /tmp/ 

 
  
