name: Code Quality Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: composer install

      - name: PHP lint
        run: php -l .

      - name: PHP_CodeSniffer
        run: vendor/bin/phpcs

      - name: PHP Mess Detector
        run: vendor/bin/phpmd . text phpmd.xml

      - name: PHP Code Beautifier and Fixer
        run: vendor/bin/phpcbf
        continue-on-error: true
