name: PHP Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:                                     
  lint:                                     
   name: PHP Lint             
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2     

     - name: Setup PHP
       uses: shivammathur/setup-php@v2            
       with:
         php-version: '>= 5.0'                  

     - name: PHP lint
       run: php -l /calcuator.php &> /tmp/ 

 
  
